baseURL: 'https://test.panjibaskoro.web.id'
title: Panji Iman Baskoro
theme: bookworm
paginate: '5'
summaryLength: '20'
googleAnalytics: ''
disqusShortname: themefisher-template
module:
  hugoVersion:
    extended: true
    min: 0.87.0
imaging:
  quality: '95'
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/line-awesome/css/line-awesome.min.css
      - link: >-
          https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/instagram-feed/instagram-feed.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
  variables:
    font_primary: Mulish
    h1: 64px
    h1_lg: 52px
    h1_md: 42px
    h2: 38px
    h2_md: 30px
    h3: 30px
    h3_md: 24px
    h4: 24px
    h5: 18px
    h6: 16px
    white: '#ffffff'
    black: '#000000'
    dark: '#152035'
    gray: '#747577'
    light: '#FAFAFA'
    color_primary: '#01AD9F'
  logo: images/logo.png
  logo_width: 200px
  favicon: images/favicon.png
  description: This is meta description
  author: Themefisher
  contact_form_action: '#'
  search: true
  mainSections:
    - blog
  copyright: 'Designed & Developed By [Gethugothemes](https://gethugothemes.com/)'
  preloader:
    enable: false
    preloader: ''
  instafeed:
    enable: false
    instagram_user: bookworm
    access_token: >-
      IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  subscription:
    enable: true
    mailchimp_form_action: >-
      https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
    title: Subscribe for our monthly newsletter.
    input_placeholder: Enter your email
  cookies:
    enable: false
    expire_days: 2
  social:
    - icon: lab la-facebook-f
      url: 'https://www.facebook.com/'
    - icon: lab la-twitter
      url: 'https://www.twitter.com/'
    - icon: lab la-instagram
      url: 'https://www.instagram.com/'
    - icon: lab la-linkedin-in
      url: 'https://www.linkedin.com/'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: aboutme/ 
      weight: 3
    - name: Contact
      url: contact/
      weight: 4
  footer:
    - name: About
      url: about/
      weight: 1
    - name: Authors
      url: author/
      weight: 2
    - name: Privacy
      url: privacy/
      weight: 3
    - name: Terms & Conditions
      url: terms-conditions/
      weight: 4
